### ISSUE TITLE
Core Criterion and Evidence Vocabularies splitting

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/CCCEV#1]
One thing that has not been developed enough in the CCEV is everything related to the Evidence. In my opinion this is a pending task: reflecting about what an evidence is and whether it has its own sub-model. 

As a matter of fact, the Core Public Service Vocabulary also models the evidence (but differently to the CCEV definition).

We'd need to come up with one sub-model of Core Evidence Vocabulary that can be reused by other Core Vocabularies and ontologies currently being defined (e.g. CPSV, CCEV, ESPD, ePO, RPaM, other).

**Comment by bertvannuffelen** [comment]
The above merge is incorrectly hooked to this issue.

**Comment by bertvannuffelen** [comment]
This is a valid remark.  In the proposed new release cccev:Evidence is very abstract. It is more like a placeholder describing it as an response to a cccev:Requirement. 
Although in terminology cccev:Evidence is bound to a cccev:Requirement: namely an Evidence is always a proof of something that has been requested. If nobody would ask for your citizenship then there would not be a document proofing your citizenship.  

In that sense, if the notion of evidence is being reused in another context, then I expect that the notion of requirement (even implicitly) is present. 
Given this tight connection between requirement and evidence it should not be placed in a separate core vocabulary.

However, the evidence as a document with all its sealing, signing, and other descriptive information can be considered a separate model. But then we best initiate first a Core Document initiative and some of those Core Documents are then Evidences. 
To give a recent example. The covid green passport is an evidence for crossing the border. This binds information of a person with a requirement in the context of some activity.  The content of the covid green passport that can be described as a sealed and signed document containing data among others about the vaccination of the person bearing the green passport. 

So to not make CCCEV the mother of all data models the proposal is to remain for cccev:Evidence as generic as possible and push the details about the Evidence to another datamodel.

**Comment by paulakeen** [comment]
The most recent development of the CCCEV insist in the fact that data are also evidences, e.g. the data provided by a Base Registry. Thus the introduction of the class cccev:Concept, as a means to specify the namespace and definition of what is being required and what is being expected in return. So considering Evidences only 'transactional documents' can be a poor approach. Additionally, there are other situations that are emerging from the LOD practice, such as the fact that data is being inferred/suggested from different Base Registry and other authoritative sources that are 'created' based on the inference of data that is linked amongst different administrations. Hence, when approaching the modelling of Evidence, in the context of the CCCEV or outside it, we should may be approach the idea of [true source of] 'knowledge' instead of 'data', 'information' or 'document'.

**Comment by bertvannuffelen** [comment]
The new proposal does not exclude the above expressed views. In CCCEV Evidence is an entity that provides proof to a requirement. I assume you mean _transactional_ with this?

Any data statement although true is not necessary an evidence. It becomes evidence when it is in relation with a requirement. 
For instance, if I have been living in strict isolated quarantine for more than 20 days it is true I am covid-free, but that is not accepted as evidence to travel. Only a recent negative test result is acceptable.  The example illustrates that there is an (implicit) prior _handshake_ on whether or not the data is acceptable. That process might be initiated by the data itself: e.g. strict quarantine could be used as evidence by video footage showing you have not left the room.  

Derived/inferred data is not excluded either. It can become evidence if the derivation is done by an trusted party in the information exchange process. But that is at the level of implementation. 

So far I fail to see in the reply a case that is blocking CCCEV to be applied, and CCCEV:Evidence to be used.

**Comment by bertvannuffelen** [comment]
The organisation of the core vocabularies specifications will not be changed. 
A consolidated diagram grouping all terminology has been discussed in the last Core Vocabularies webinar (dec 2021).  This should facilitate the reuse and understanding.
