### ISSUE TITLE
Consider Signatures and Seals for Evidence

### ISSUE THREAD

**Issue by SusanneWigard** [SEMICeu/CCCEV#10]
In many practical applications (specifically: EFTI) an evidence is just a document carrying a stamp or signature. 
When modeling this in the digital world, the document is often a scanned document with a hand-written signature. 
We should however (at least for the XML representaiton) also consider catering for digital signatures or seals. 
This would be a natural element of an evidence.

**Comment by bertvannuffelen** [comment]
A question to the community, in the light of an upcoming new release of CCCEV. Are these topics to be included as part of CCCEV?

As @SusanneWigard  suggested is an Evidence something that must be signed or sealed? Or can it be a value given by a trusted party (e.g. in a closed data exchange environment). 

In the upcoming release of CCCEV the requirement for signing or sealing to be an Evidence is not included.

**Comment by SellittoGiampaolo** [comment]
A seal / a signature on the evidence allows to store the evidence and preserve its validity outside the boundaries of the interchange platform, where trust between Evidence Consumer and Evidence Issuer is estabilished and maintained by the system itself.

**Comment by bertvannuffelen** [comment]
Digital trust of the exchange channel and shared information are kept outside scope for CCCEV. This is usually tied technical agreements of the implementers. And therefore this topic is considered outside scope.
