### ISSUE TITLE
Some real world Use Case

### ISSUE THREAD

**Issue by SellittoGiampaolo** [SEMICeu/CCCEV#11]
Let's try to have some simple Use Case, covering all the informative needs and possible complex scenarios without clogging them with details or consolidated practices that can distract the attention from the kernel of the problem.

If possible, i'd choose a realistic scenario for the RedAlert movements in EU during these days.

As you know, Italy has limited movements of citizens in  and out of some territories in order to mitigate the contagion risk and the spreading of COVID-19.

To be allowed to travel, Citizens must met some criteria (Exclusion Grounds and Selection Criteria).
They can self declare the fulfillment of these criteria and authorities can check the veracity of self declarations. If they are proven to be false, you can be fined and convicted.

Criteria are varying from day to day, since the alert level is increasing.

We can have simple scenarios, but also pretty complex scenarios in terms of criteria and evidences.

The common exclusion ground is "Infected" or "Quarantine".
If you are Infected or in Quarantine you cannot travel.
For simplicity, we only consider Quarantine as "Resident in a RedAlert Zone" and it is a quality that can be checked in a simple manner querying Resident Pupulation Register (Anagrafe Nazionale Popolazione Residente, in Italy).
If you are not Quarantine, you can travel responsibly.
Selection Criteria for Traveling Responsibly are the following:

1. You are going to your workplace/Traveling for work (check a mandate from the Legal Representative of your Business, let's say there is a Register of the "Pass4WorkReasons")
2. You are going to the Hospital for Healthcares (register of the HealthCare)
3. You are going to your Parent's home, which are elder than 70 or cannot travel (Register of the Resident Population or Register of the not Self-Sufficient People)

These conditions are complex enough to cover any case of Criteria Mix.

We can immediately realize that a group of criteria is a Logical Expression (Boolean) that for this simple scenario can be represented in terms of Calculus of Predicates.

example: TRAVEL< -- notQuarantine AND (Pass4WorkReasons OR HealthCare OR ( OldParents OR notSelfSufficientParents) 

I remained on Predicate Calculus since it is well behaved in terms of computation - we will always arrive at a response which is TRUE or FALSE, checking on the Evidences Database

**Comment by bertvannuffelen** [comment]
Thank your for your example. To illustrate the upcoming new release of CCCEV another domain has been chosen. If you have in the mean time implemented the above in a pilot or application you are welcome to share it.
