### ISSUE TITLE
Core Criterion Vocabulary evolution

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/CCCEV#2]
The works done in different fora (ESPD, ePO, UBL, eForms, RPaM) have led to an optimisation/evolution of the CCEV currently published on Joinup.

This optimisation/evolution looks like this (last version published on the [ePO GitHub](https://github.com/eprocurementontology/eprocurementontology/wiki/Conceptual-Model-v2.0.1#criterion-)):

![criterion](https://user-images.githubusercontent.com/16134316/48216936-4f475d80-e386-11e8-96d6-25116eca08d4.jpg)

Notice that in this model the semantics of requirements and expected responses are now expressed by means of properties the range of which is now one single class "CriterionProperty". 

This has impacts not only on the current version of the CCEV vocabulary but also on the CPSV vocabulary (Public Service hasCriterion CriterionRequirement). 

We propose to start a discussion, under this very issue, to review this approach being used in ePO and that we want to propose for its inclusion in OASIS UBL-2.3.

**Note**: Beware that some of the code lists (expressed as enumerations in the diagram above) are domain-specific (e.g., as the diagram is taken from ePO the code list "Legal Basis Identifier" is a list of "codes" (in purity of ideas) to be published by the "[Publications Office of the European Union](http://ec.europa.eu/ipg/basics/management/day_to_day/opoce/index_en.htm) (OP)", in the [EU Vocabularies](https://publications.europa.eu/en/web/eu-vocabularies/) Metadata Registry (MDR) section Public Procurement.

**Comment by paulakeen** [comment]
When trying to apply the CCCEV model (presented above in the previous comment) in other business domains we have realised that it could slightly improved in the following ways:

1. The "ccev:hasLegalBasis cccev:Legislation" should be generalised as "ccev:derivedFrom ccev:ReferenceFramework". Rationale: criteria are practically always based of principles, recommendations, requirements, etc. used for the definition of one of more criteria. A framework then may be be composed of one or more reference sources, such as legal acts, standards and specifications, ICT policy works (e.g the EIF within the EIS), or just the knowledge, experience and good practices of the criteria authors. Design: Ideally, we think that the ReferenceFramework class would be an extension of an Asset that in turn extended the rdf:Resource and that had aspects of Work, Expression, Manifestation and Items as defined in the IFLA LRM (FRBR) model. Unfortunately we're limited to reuse the current ADMS Asset, which is defined as a dcat:Dataset thus casting a confusing way of approaching the semantics and attributes of what an Asset should be. But that is another discussion in another context (ADMS).

2. It should be possible to apply general constraints to the whole criterion, but also one or more constraints to a group of information requirements and to a particular information requirement. 

![image](https://user-images.githubusercontent.com/16134316/67895902-9dd3a600-fb5b-11e9-953c-011843086ca5.png)

**Comment by paulakeen** [comment]
We have been looking into the fantastic work done by [TOOP regarding the CCCEV](http://wiki.ds.unipi.gr/display/TOOP/ISA+Core+Voc+Data+Model).

In this work they compare one of the proposals posted in this issue with their own information requirements and propose extensions to the CCCEV. The figure below shows them:

![image](https://user-images.githubusercontent.com/16134316/69169014-f1e8ff00-0af7-11ea-8505-ca54ef6207a1.png)

Here you have our comments to the TOOP proposal:

1.  Notice that we are now proposing to replace the eli:LegalResource with cccev:ReferenceFramework. The reason is that, for a core vocabulary, not all the criteria are derived from legislation, but could derived from other sources, e.g. standards, specifications, generic frameworks such as the EIF, etc.

2. We do agree, and like very much, the extension you propose of having the EvidenceType in the CCCEV, this way you can cross-check that what is "normative" to use is "actually" being used. One Use Case that illustrates this situation is the e-Certis + ESPD Response tandem: what MS maintain in e-Certis are types of evidences, and what the Economic Operators provides are instances of evidences that should be the ones indicated in eCertis. However we miss a link between the EvidenceType and the Agent that is the authority responsible for issuing it. Unless we decide that EvidencyType inherits from the ADMS Asset concept (a dcat:Dataset class), which would solve the problem and makes a lot of sense to us.

2. About the EvidenceSource: If Evidence inherited from ADMS Asset (or had aspects of an Asset) then we can get rid of the EvidenceSource and everything on the right, as the source would be the "dcat:distribution".

3. If by "Provider" of the Evidence is the Agent that distributes the instances of Evidence, and Evidence is an ADMS Asset, then (1) the triple "cccev:Evidence dct:publisher foaf:Agent" can be used to specify who is the authority responsible for the Evidence and "cccev:Evidence dcat:distribution dcat:Distribution + dcat:Distribution dct:publisher foaf:Agent" is logically reserved for the Evidence Provider. See the [ADMS vocabulary](https://github.com/SEMICeu/ADMS-AP/blob/master/releases/2.01/adms-ap_version_2.01.png).

This would then be a new proposal, which simplifies even more the latest proposal (see comment above) and would satisfy the TOOP requirements:

![image](https://user-images.githubusercontent.com/16134316/69171653-a84ee300-0afc-11ea-925c-688b8779cca8.png)

**Comment by paulakeen** [comment]
After several meetings between TOOP, e-Certis, SEMIC, and other stakeholders, we see new possibilities for the evolution of the CCCEV as as a "specialisation" of more generic model which conflates the needs of TOOP and those of the e-Certis multidomain while preserving the requirements from eProcurement, amongst other possibilities.

![image](https://user-images.githubusercontent.com/16134316/74590539-999a9e00-500f-11ea-8365-ec823c818e94.png)

**Comment by paulakeen** [comment]
### Reuse of the above model by the TOOP-EDM (Exchange Data Model):

![image](https://user-images.githubusercontent.com/16134316/74594717-bc41ac80-5039-11ea-97fa-6310331a36f9.png)

### TOOP Document or Data Request 

![image](https://user-images.githubusercontent.com/16134316/74594726-e1ceb600-5039-11ea-9401-8a3e03c00079.png)

### TOOP Document or Data Response

![image](https://user-images.githubusercontent.com/16134316/74594736-ef843b80-5039-11ea-89e0-949d9b231775.png)

**Comment by paulakeen** [comment]
After F2F meetings in BRU with TOOP, SEMIC, ePO, SDG, eCertis and other stakeholders, we have come up with this more simplified version of the CCCEV:

![image](https://user-images.githubusercontent.com/16134316/75326929-ce162180-587b-11ea-9fbb-82e5fd873218.png)

**Comment by paulakeen** [comment]
This figure below would illustrate "an instance" of a criterion in a Response document:

![image](https://user-images.githubusercontent.com/16134316/75328249-00c11980-587e-11ea-8bce-af4561a88b37.png)

**Comment by paulakeen** [comment]
Slights changes after meeting today with TOOP, ePO, SEMIC, and other. We'll come up soon with definitions:

1. Constraint is now a subclass of Requirement. Hence it has concepts and response values, and it could be supported with data or documentary evidence types and evidences, if needed (could be a rare case).
2. Each concept, specially complex data element concepts can be seen as (represented by) types of evidences.
3. Observe that the EvidenceType and the actual Evidence are provided by requested (most probably authoritative) DataService(s) through their base class adms:Asset.
4. The property cccev:conformsTo can be seen redundant as it could be implemented using the dcat:qualifiedRelation from dcat:Dataset to dcat:Dataset. Let's discuss it.

![image](https://user-images.githubusercontent.com/16134316/75353936-780da200-58ac-11ea-8154-45b442601948.png)

**Comment by bertvannuffelen** [comment]
A quick note on the the approach of the _cccev:concept_. 

This is pattern in which the attributes of a class are fully objectified. Instead of a direct value
```_:req1 domain:attr "value"```
an object structure is being defined:
```
_:req1 cccev:hasAttr _:attr1.
_:attr1 cccev:attrName "attribute".
_:attr1 cccev:ID "anAttribute".
_:attr1 cccev:namespace "https://mydomain/ns/ontology#".
_attr1  cccev:type  <someCategory>.
_attr1 cccev:responsValue _:attr1value1.
_attr1value1 cccev:hasDatum "value".
```

Note that the rectangle cccev:Value is misleading, because according to the drawing language it should be an object. So an additional indirection.

This is a wellknown pattern, but I would like to avoid to make a relationship with SKOS for cccev:Concept.

Positive on the pattern is that the model shows the extendability of the schema. However one can question if that should be part of the model. One can take that also in the implementation: e.g. json APIs assume this flexibility. Therefore adding new terms is done at zero cost. Or extra terms can be part of the payload. 
Another drawback of this approach is that the list of allowed attributes and their meaning is spread over additional documentation which should be carefully interpreted with regard to the allowed values in the responses. So it is shifting the complexity of the interpretation of the rules and constraints to an interpretation of some new language (the cccev attribute speficification language). 
Maybe here one could include modeling rules like subclassing and how the attributes have to be specified. And work with more "application profiles/implementation models per kind of criterion".

**Comment by paulakeen** [comment]
A new version of the CCCEV and of the TOOP-EDM use case is now available in this GH code repository. 

### The CCCEV looks now like this:
![image](https://user-images.githubusercontent.com/16134316/75763944-678e7900-5d3d-11ea-9d2a-9d9168775f8f.png)

### The TOOP EDM:
![image](https://user-images.githubusercontent.com/16134316/75763980-79701c00-5d3d-11ea-832e-826bbe365128.png)

### The TOOP-Request details:
![image](https://user-images.githubusercontent.com/16134316/75764082-9e648f00-5d3d-11ea-8f9b-ba089afbb952.png)

### The TOOP-Response details:
![image](https://user-images.githubusercontent.com/16134316/75764094-a3294300-5d3d-11ea-8c49-cf6dbaecc823.png)

**Comment by paulakeen** [comment]
The XSD for the CCCEV can be downloaded from the GH code repository: https://github.com/SEMICeu/CCCEV/blob/CV-2.0.0/cccev/2.0.0/xml/cccev-2.0.0.xsd

**Comment by paulakeen** [comment]
1. Correction needed: We agreed that Requirement should be renamed back to InformationRequirement.
2. Proposal: What would be the problems if we moved all the attributes and properties of Concept to "InformationRequirement" and got rid of Concept? For a starter I see three advantages: 1) the model gets simpler; 2) we don't have to define "Concept", which sincerely I was kind of scared of; and 3) Some more granular information requirements could have their own  evidences.

Reactions welcome!

**Comment by lbota** [comment]
If we remove Concept the redundant bijective property "cccev:representsConcept / cccev:isRepresentedBy" would be also removed thus eliminating possible inconsistencies that would be generated by the fact that cccev:InformationRequirement were linked to a cccev:EvidenceType instance that is not in the correct cccev:EvidenceTypeList.

**Comment by lbota** [comment]
Another problem related to cccev:Concept is that we would need to constraint the Concept, not the cccev:InformationRequirement (at least in ESPD). This modification wouldn't be necessary if we remove the cccev:Concept class, as suggested in the comment above.

**Comment by paulakeen** [comment]
Latest discussions with the WG (20200317) cast this other approach, which intends to align e-Certis, SDG, eProcurement, and other "scenarios".

![image](https://user-images.githubusercontent.com/16134316/76856649-f62dea80-6853-11ea-9d65-e9bae159fce8.png)

**Comment by jerouris** [comment]
Hi Enric,
So the difference now between this and that https://github.com/SEMICeu/CCCEV/issues/2#issuecomment-593864412 is the unlinking of the evidenceType and Evidence with the Concepts?
Or this is somewhere inferred (for example I see the datasetType stating something like structured data)

**Comment by paulakeen** [comment]
1- About the EvidenceType: I thought that this approach would better reflect the OR clause you have in the ppt you presented , but additionally it would introduce the possibility of defining as many EvidenceRequirements as different types of "expected evidences" are necessary, some of type "document" some of type "structured data". The AND and OR would be controlled as in the previous proposals: the types in one EvidenceTypeCombination would be AND and different Combinations would be combined via OR. But I see now that this may not work properly. So I suggest going back to this other (previous approach), being the main difference that the list of types of evidences is now attached to the criterion, as suggested by Giampaolo (and as done in ESPD) (DataSet and Agent are not included in order to simplify the diagram and focus only on the criterion)

![image](https://user-images.githubusercontent.com/16134316/76879086-08b91b80-6876-11ea-8007-18548bde04a4.png)

**Comment by paulakeen** [comment]
New iteration, based on the works by TOOP and SEMIC and meetings with e-Certis, ePO, ESPD, and experts working for COM. 

In this new iteration, we have a central class, which is Requirement, and three specialisations of it: Criterion, Information Requirement and Constraint, which can be seen as specific types of requirements, and are thought to be used depending of the Use Case. Thus Criteria is used, and supported by the Procurement legislation (Reference Framework are here Directives and National Law, plus EU Regulations like the ESPD Regulation and other). Information Requirement is a good candidate for the SDG Use Case, as it defines the types of evidences that are going to be required to consume a Public Service. Constraints are requirements imposed on other requirements. 

The EvidenceTypeList, taken from the e-Certis change request, is used as in previous iterations to produce combinations of AND-conjuncted EvidenceType cum optional OR-conjuncted EvidenceTypeList.

Concepts are used to define questions (as in ESPD) or known ontology-based entities that need to be requested to a base registry. The respon values to these questions represent actual Evidences: in the case of the ESPD they are evidences because the ESPD is a self-declaration that wil, timely, be accompanied by supporting documents provided by the Economic Operator; and in SDG they are evidences because the response values are provided by authoritative registries.

A simplified view follows, and another diagram containing the relationship of the CCCEV to DCAT-AP is also provided below. Beware that critical classes like Evidence, EvidenceType and FrameworkReference are subclasses of dcat:DataSet (i.e. Assets!). Therefore, many relevant properties for the CCCEV and to establish relationships between themselves are inherited from DCAT-AP.

Simplified view:

![image](https://user-images.githubusercontent.com/16134316/77458364-5e557100-6dfe-11ea-9063-e110d33e84f1.png)

View including DCAT-AP entities:

![image](https://user-images.githubusercontent.com/16134316/77458708-ed628900-6dfe-11ea-9774-be3b9a86ec5e.png)

**Comment by paulakeen** [comment]
Sorry, the above diagrams contains errors that have been corrected later. Here you have the corrections:

**Simplified (not DCAT-AP included):**

![image](https://user-images.githubusercontent.com/16134316/77917394-d0183980-729a-11ea-9cab-cbd19784178f.png)

**DCAT-AP included:**

![image](https://user-images.githubusercontent.com/16134316/77917490-ea521780-729a-11ea-94c8-a570bb3cf3b9.png)

**Comment by paulakeen** [comment]
Please consider this late update (see also [CCCEV XSDs](https://github.com/SEMICeu/CCCEV/tree/CV-2.0.0/cccev/2.0.0/xml) and example [XSD](https://github.com/SEMICeu/CCCEV/blob/CV-2.0.0/ndr/Criteria-Polymorphism-example.xsd) and [XML](https://github.com/SEMICeu/CCCEV/blob/CV-2.0.0/ndr/ESPD-Crierion-example.xml) in the code repository):

![image](https://user-images.githubusercontent.com/16134316/78179628-d0aefc80-7461-11ea-8dde-d25bf1e24bb0.png)

**Comment by SellittoGiampaolo** [comment]
In my opinion something is still missing:
The evidence is an evidence of the _fact_ that <<someone/something fulfills a criterion>>, not of the criterion itself. 
This concept is not represented here, ora at least it is me that do not catch the link between the agent, the distribution and the distribution of the criterion

**Comment by paulakeen** [comment]
@SellittoGiampaolo, we'll take into account your comment in the XML example we are preparing for the ESPD use case. Thank you for the remark.

**Comment by paulakeen** [comment]
Late update of the model follows ([eap](https://github.com/SEMICeu/CCCEV/blob/CV-2.0.0/cccev/2.0.0/uml/cccev_v2.0.0.EAP) file and [CCCEV xsds](https://github.com/SEMICeu/CCCEV/blob/CV-2.0.0/cccev/2.0.0/xml/cccev-2.0.0.xsd)are available in the code repository).

### Simplified view:
![image](https://user-images.githubusercontent.com/16134316/78951652-283d1000-7ad3-11ea-9dd0-83091786a7ed.png)

### With DCAT-AP entities included
![image](https://user-images.githubusercontent.com/16134316/78951663-325f0e80-7ad3-11ea-8184-dcd555902986.png)

**Comment by JosePRevenga** [comment]
Latest update CCCEV's model follows ([eap](https://github.com/SEMICeu/CCCEV/blob/CV-2.0.0/cccev/2.0.0/uml/cccev_v2.0.0.EAP) file and CCCEV [XSDs](https://github.com/SEMICeu/CCCEV/tree/CV-2.0.0/cccev/2.0.0/xml) are available in the code repository).

Most relevant changes are summarised as follows:
- **cagv:Agent** has been replaced by foaf:Agent, as the development of the former is currently not foreseen. This implies that any additional data or object property required by the domain business is to be defined by the domain.
- A new relation **cccev:isAbout** has been created between cccev:Evidence and foaf:Agent, making now it possible to specify the data subjects of the Evidences.
- **cccevDocumentReference** is now a specialisation of dcat-ap:Dataset, instead of dcat-ap:Distribution. This is meant to enrich the class while making still possible to "reach" dcat-ap:Distribution class through dcat:distribution relation.

**Simplified view**:
![CCCEV](https://user-images.githubusercontent.com/55392132/88526031-b7772080-cffb-11ea-8be0-42930438d667.png)

**With DCAT-AP entities included**:
![CCCEV+DCAT+AGENT](https://user-images.githubusercontent.com/55392132/88526085-c52ca600-cffb-11ea-8767-8fadc6263eab.png)

**Comment by bertvannuffelen** [comment]
This issue has been used as part of the design discussions for the new release of CCCEV. With the public review starting soon on the new release, this issue is closed to have the reviewers discuss on the proposed specification and not being confused with older proposals presented in this issue.
