### ISSUE TITLE
Agent roles for CCCEV

### ISSUE THREAD

**Issue by barthelemyf** [SEMICeu/CCCEV#29]
The proposed release 2.0.0 of CCCEV has limited the number of adopted agent roles. With this issue we welcome the community to provide feedback on the agent roles that are not mentioned but are valuable to be included in CCCEV.

**Comment by dimi-schepers** [comment]
During the webinar dd. 2021-03-30, the CCCEV Working Group a suggestion was made to include a {Evidence isProvidedBy Agent} relationship. In the domain of procurement, for example, you have intermediaries who provide the evidence, which can be different from the ones who have issued it.

There was a general agreement from the participants and no objections were made w.r.t. this addition, so far.

**Comment by bertvannuffelen** [comment]
The CCCEV 2.0.0 includes now 3 common agent roles: creation, issuing and providing. These correspond to the most used situations.
