### ISSUE TITLE
Temporal information for CCCEV

### ISSUE THREAD

**Issue by barthelemyf** [SEMICeu/CCCEV#30]
Often decision-making is based on temporal information. In the proposed release 2.0.0 of CCCEV, the temporal information has, so far, not been included in the core model. We welcome with this issue any feedback on whether temporal information should be included as part of the core model and, if yes, which information.

**Comment by dimi-schepers** [comment]
During the webinar dd. 2021-03-30, there was general agreement from the Working Group to include temporal information within CCCEV v2.0.0. More specifically, this results in an addition on both sides of the model:
1. a Requirement should be able to ask some validity period on the Evidence (e.g. a certificate of good conduct cannot be issued more than 3 months ago);
2. an Evidence should be able to contain an expiration date.

**Comment by bertvannuffelen** [comment]
In the new version of CCCEV these properties have been added.
