### ISSUE TITLE
Transformation for structured evidence

### ISSUE THREAD

**Issue by PimvanderEijk** [SEMICeu/CCCEV#33]
Sometimes a structured evidence type has more information than strictly needed to satisfy a requirement. In this case it would be useful if the evidence type could be associated with a transformation that filters the structure such that the output is limited (or customized) to the requirement.  

For example:   it may be relevant to know whether a natural person if an adult at a particular point in time.   This fact can be proven by a birth certificate,  but this could have irrelevant information,  such as the identities of the parents,  place of birth, or the exact date of birth is not relevant.  A transformation could change a structure like "<BirthDate>2000-01-01</BirthDate>" to "<AgeVerification><ReferenceDate>2020-01-01</ReferenceDate><IsAdult>true</IsAdult></AgeVerification>". 

In SDG, this feature could be used to obviate the need for specialized evidence types.  The requested transform would be specified in the evidence request.  The evidence provider should apply the transformation before returning the evidence to the requester.

The transformation could be identified by an identifier from a known/agreed set of transformation identifiers with known/agreed semantics.   (For each such transformation, a reference implemention of an XSLT stylesheet that performs the transformation could be provided, but how a user would implement the transformation would be up to them). 

This feature addresses minimization requirements without having to create a huge amount of specialized evidence types.

**Comment by sethvanhooland** [comment]
Thanks Pim.  It's an important feature of the SDGR implementation. The approach you suggest ("The transformation could be identified by an identifier from a known/agreed set of transformation identifiers with known/agreed semantics") is good but also raises the challenge of what we consider as "known/agreed". Creating the identifiers will be a gradual effort as we gather input form MS, so we could get started with a limited approach, do some early prototyping and enhance in an iterative manner and add complexity as we go along. However, it's implementation work which could be foreseen in the light of a specific AP for the SDGR

**Comment by paulakeen** [comment]
Indeed, the indication of how to transform the evidence should be part of an “Application” profile. The Core Vocabulary should remain agnostic of how the content it conveys is used.

**Comment by bertvannuffelen** [comment]
Although the usecase has not been integrated as part of CCCEV, there are now in CCCEV 2.0.0 hooks and supportive structures that facilitate the usecase. 

The ability to express an Information Concept as a request for specific information, being answered by a Supported Value which can be derived from the supplied Evidence as the base framework to address this usecase. 

In the Information Concept, the expected value can be defined in a serialization of any implementer's language of choice. This value can be supplied via the Supported value, as a corresponding value extracted from the supplied evidence data e.g. by some process at the evidence provider side, or it could be supplied as a query in a commonly agreed language.

This of-course does not cover complex transformations. The needs and requirements of these will be likely implementation specific. For now this is considered out of scope, but implementations are welcome to submit there usage and information models to improve CCCEV.
