### ISSUE TITLE
Bidirectional relationships

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/CCCEV#34]
During the webinar dd. 2021-03-30,  the question was raised whether there really is a need for the symmetric (inverse) relationships  within the model.

It was clarified that they are indeed not needed from a purely semantical perspective. There are however use cases where the queries might go in two directions and there is no generally preferred direction, e.g. start from atomic requirements and go up versus start from general requirements and drill down. When this was the case, both directions were included.

This is however an open discussion point and we invite the Working Group to challenge the need for bidirectional relationships.

**Comment by bertvannuffelen** [comment]
Since no additional requests have been made to this topic by the community, no additional relationships (bidirectional) are included.
