### ISSUE TITLE
Various issues with the Enterprise Architect (EAP) distribution 

### ISSUE THREAD

**Issue by SusanneWigard** [SEMICeu/CCCEV#4]
Some changes that would help with the automated creation of XML schemas, but also contribute to the general quality of the distribution:  

- all properties should be public
- all properties should have a type  
- (properties that are not associations currently have no type at all defined)
- - fulfilled indicator should  be Boolean
- - weight should be numeric
- - start time and end time should be datetime
- - language should be a code list
- - the others probably should be stirngs

- package name and all properties should be UpperCamelCase (not strictly necessary for the      UML diagram but it would help with auto-generation of tehcnical representaitons (XML can ave no blanks in attribute names) -  e.g. criteriontype, fulfilled indicator, all association names 

- Agent, Person and Organisation should be in their own package (cva) , (Not important for UML diagram as such but agagin would help wiht the generation of  technical representations. 
- FormalFrameworkType should also be in its own package (cpsvap)

- Organisation should be called Business (at least that's what it called in the lated release of the Core Vocs XML schemas)

- definitions should be in the Model (as comments) 
- cardinalilties should be in the Model
- the model should have a more specific name (cccev)

Some issues not related to XML creation but to the general logic of the model: 
- 	fulfilled Indicator should actually be fulfilment Indicator
- 	property "provided" of Agent should be "isProvidedBy" of RequirementResponse (it is not    really the RequirementResponse a property of the Agent but rather the Provider is a property of the RequirementResponse)
- 	property "satisfies" of Agent should be removed (that the Agent satisfies a reuirement is inplicit in the Agent providing the RequirementResponse)

**Comment by bertvannuffelen** [comment]
The EAP file included is a version that supports an implementation neutral representation. Some considerations reflect semantical issues (like missing cardinalities, or misspellings), they have been corrected in the new release.
