### ISSUE TITLE
Add more rdfs:label in the ontology

### ISSUE THREAD

**Issue by gatemezing** [SEMICeu/CCCEV#43]
Hello, I've been looking at the RDF file in Turtle here https://semiceu.github.io/CCCEV/releases/2.00/voc/cccev.ttl and realize there are almost no labels associated to classes and properties. IMHO, for tools consuming the ontology, it would be great to add such labels. 

Example:
```
<http://data.europa.eu/m8g/weightingConsiderationDescription> a owl:DatatypeProperty,
    rdf:Property; rdfs:label "Weighting consideration description"@en ;
```
...

**Comment by bertvannuffelen** [comment]
@gatemezing thanks for notifying this item. We added the missing labels.
