### ISSUE TITLE
Retrieving data via data.europa.eu/sparql

### ISSUE THREAD

**Issue by ioggstream** [SEMICeu/CCCEV#44]
## I expect

to retrieve vocabularies from the data.europa.eu/sparql endpoint

## Because

I want to integrate and validate information and vocabularies with the ones provided by this repo

## Reproduce

The following query returns an empty result.

```
select distinct * where {
<http://data.europa.eu/m8g/Criterion> ?p ?q
} LIMIT 100
```

**Comment by bertvannuffelen** [comment]
The data.europa.eu sparql endpoint only contains DCAT-AP instances from whole Europe. 

Therefore the result is empty, as expected.
