### ISSUE TITLE
Align with CPSV-AP

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CCCEV#5]
in the UML class diagram there is Formal Framework which has been deprecated in CPSV 2.2 in favour of Legal Resource from the Eli ontology

**Comment by SusanneWigard** [comment]
I've made a comparison of the present versions: https://webgate.ec.europa.eu/CITnet/confluence/download/attachments/866414818/CCCEV%20comparison.docx?version=1&modificationDate=1565020729573&api=v2
(internal link, just for the SEMIC team)

**Comment by bertvannuffelen** [comment]
The consolidated diagram presented during the Core Vocs webinar 2 dec 2021 provides an alignment.

**Comment by EmidioStani** [comment]
This issue can be closed, follow up discussion can continue on the CPSV-AP issue:

https://github.com/catalogue-of-services-isa/CPSV-AP/issues/61
