### ISSUE TITLE
http://data.europa.eu/m8g/hasSupportingEvidence absent from RDF representation of voc

### ISSUE THREAD

**Issue by saxomoose** [SEMICeu/CCCEV#54]
`http://data.europa.eu/m8g/hasSupportingEvidence` appears to be absent from the RDF representation of the voc.

I refer to:

- https://raw.githubusercontent.com/SEMICeu/uri.semic.eu-puris/main/releases/m8g/m8g.ttl
- https://semiceu.github.io/CCCEV/releases/2.00/voc/cccev.ttl

Not immediately clear which is the authoritative link.

**Comment by EmielPwC** [comment]
Thank you for your notification of the issue.

We found the root cause of the issue and updated the release accordingly 

[the authoritative link is https://semiceu.github.io/CCCEV/releases/2.00/voc/cccev.ttl](the authoritative link is https://semiceu.github.io/CCCEV/releases/2.00/voc/cccev.ttl
)
