### ISSUE TITLE
Property applicableinPeriodOfTime is not proper lowerCamelCase.

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/CCCEV#7]
The property applicable**in**PeriodOfTime of CriterionRequirement should be applicable**In**PeriodOfTime.

**Comment by SusanneWigard** [comment]
This is true for several other attributes as well - see also issue #4

**Comment by bertvannuffelen** [comment]
this property is part of CCCEV version 1.0. No change in the past will be made, as CCCEV 1.0 will be deprecated. The change will be only be done on explicit request by the Community.
