### ISSUE TITLE
Conneg issue?! - Can't get a Turtle serialization with Curl

### ISSUE THREAD

**Issue by gatemezing** [SEMICeu/CCCEV#8]
A curl request for Turtle version `curl -i -H "Accept: text/turtle" http://data.europa.eu/m8g/cccev `almost give me back HTML version.  Any help? My final goal is to [submit the vocab into LOV](https://lov.linkeddata.es/dataset/lov/suggest) without error. TIA.

**Comment by bertvannuffelen** [comment]
We are working on making the URIs of the core vocs dereferenceable. We keep you posted. For now I close this issue.
