### ISSUE TITLE
Some potential issues with expression CCCEV in XML schema

### ISSUE THREAD

**Issue by SusanneWigard** [SEMICeu/CCCEV#9]
Collecting here just some considerations for the team when they create an XML reüpresentation: 

•	The way that PersonType and OrganisationType are generalisations of AgentType (in the UML diagram of hte version pubisled on Joinup) is not really modelled in the Core Vocabularies Aggregate Components (CVA) schema, therefore if we just imported that schema and used its AgentType,  users wouldn’t be able to replace an agent by a person or an organisation in an instance document.
•	Also, in the CCCEV UML diagram we have OrganisationType but in the CVA schema this is called CoreBusinessType. 
•	Capitalization in the UML diagram is (mopstly) lowerCamelCase, but the CVA schema uses UpperCamelCase. There should be a common set of Naming and Design Rules for all Core Vocabularies. 
•	From the UML diagram it is not evident what would be the root element of an XML instance document – this would depend on what you use the vocabulary for, but if people would want to validate an instance document against a schema they need to have a root element. Following UBL naming and design rules, all the schemas should be split into several files, where the global complex types would be in AggregateComponents. This can then be imported to other schemas which define root elemens as they please.

**Comment by bertvannuffelen** [comment]
See https://semiceu.github.io/CCCEV/releases/2.00/#implementation-note. As CCCEV aims to be implementation neutral, implementation considerations (like syntax or root element) are out of scope for the core vocabulary. Nevertheless it is important to see and understand how CCCEV is being used in practice and therefore feedback or experienced challenges are welcome to be noted, but not all can be addressed at this level.
